---
name: Development build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}

      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0

      - name: Download go dependencies
        run: go mod download

      - name: Run build
        run: go build -o webhook

      - name: Build Docker image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: .
          push: false
          tags: ${{ github.repository }}:latest
